# Generated by Django 2.2 on 2021-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='speciality',
            field=models.CharField(default='non-existent', max_length=75),
            preserve_default=False,
        ),
    ]
