# Generated by Django 3.1 on 2021-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Test', max_length=75),
            preserve_default=False,
        ),
    ]
