# Generated by Django 2.2 on 2021-07-30 01:03

from django.db import migrations, models
import minireg_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('minireg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, null=True, validators=[minireg_app.models.email_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=55, null=True, validators=[minireg_app.models.password_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
